---
- name: Install Mysql package
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
   - mysql-server
   - python-mysqldb

#- name: Configure SELinux to start mysql on any port
#  seboolean: name=mysql_connect_any state=true persistent=yes
#  when: ansible_selinux.status == "enabled"

- name: Copy the my.cnf file
  template: src=mysqld.cnf.j2 dest=/etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
   - restart mysql

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host={{ app_host }} state=present
